In [1]:
#Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Read dataset to pandas dataframe
leuanalysis_data = pd.read_csv('./leuanalysis3.csv')
leuanalysis_data.head()

CELL  SMEAR  INFIL   LI  BLAST  TEMP  REMISS
0   0.8   0.83   0.66  1.9   1.10  1.00       1
1   0.9   0.36   0.32  1.4   0.74  0.99       1
2   0.8   0.88   0.70  0.8   0.18  0.98       0
3   1.0   0.87   0.87  0.7   1.05  0.99       0
4   0.9   0.75   0.68  1.3   0.52  0.98       1

In [11]:
#Identify how many classes we have
leuanalysis_data.REMISS.unique()

array([1, 0], dtype=int64)

In [4]:
leuanalysis_data["REMISS"].value_counts()

0    18
1     9
Name: REMISS, dtype: int64

In [14]:
# Assign data from first four columns to X variable
X = leuanalysis_data.drop('REMISS',axis=1).values
y = leuanalysis_data['REMISS'].values

#Train the Data
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,test_size = 0.20,random_state=100)

#Scale the data
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)

In [16]:
import collections, numpy
collections.Counter(y_test)

Counter({0: 4, 1: 2})

In [10]:
#Neural Network
from sklearn.neural_network import MLPClassifier  
mlp = MLPClassifier(hidden_layer_sizes=(12, 8, 1), max_iter=10000,random_state=100)  
mlp.fit(X_train, y_train) 
predictions = mlp.predict(X_test) 

#Evaluate the Neural Network Algorithum
from sklearn.metrics import classification_report, confusion_matrix  
target_names=['Class 0','Class 1']
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions,target_names=target_names)) 

[[3 1]
 [2 0]]
              precision    recall  f1-score   support

     Class 0       0.60      0.75      0.67         4
     Class 1       0.00      0.00      0.00         2

    accuracy                           0.50         6
   macro avg       0.30      0.38      0.33         6
weighted avg       0.40      0.50      0.44         6



In [18]:
#Script for Decision Tree
from sklearn.tree import DecisionTreeClassifier  

for name,method in [('DT', DecisionTreeClassifier(random_state=100))]: 
    method.fit(X_train,y_train)
    predict = method.predict(X_test)
    target_names=['Class 0','Class 1']
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict,target_names=target_names)) 


Estimator: DT
[[3 1]
 [2 0]]
              precision    recall  f1-score   support

     Class 0       0.60      0.75      0.67         4
     Class 1       0.00      0.00      0.00         2

    accuracy                           0.50         6
   macro avg       0.30      0.38      0.33         6
weighted avg       0.40      0.50      0.44         6

